<#
.SYNOPSIS
Applies a repo-rename workspace bundle on a target machine.

.DESCRIPTION
Reads a bundle generated by `sync-repo-rename-workspace.ps1` and can:
- rename local repo folders from old name to new name,
- replace local `.code-workspace` files with patched versions,
- update git `origin` URLs to the new repository slug.

Safe by default: if `-Execute` is not passed, the script runs in WhatIf mode.

.PARAMETER BundlePath
Path to a specific rename sync bundle folder.

.PARAMETER SyncRoot
Root where bundles are stored. Used when BundlePath is omitted.

.PARAMETER BundleName
Bundle name prefix used to auto-select the newest bundle.

.PARAMETER WorkspaceSearchRoots
Candidate roots that contain local `.code-workspace` files.

.PARAMETER RepoSearchRoots
Candidate roots that contain local repositories.

.PARAMETER GitHubOwner
Owner to use when rewriting origin URLs. If omitted, owner is inferred from current origin URL when possible.

.PARAMETER SkipRepoRename
Skip local folder rename operations.

.PARAMETER SkipWorkspaceUpdate
Skip local `.code-workspace` replacement operations.

.PARAMETER SkipGitRemoteUpdate
Skip git `origin` URL updates.

.PARAMETER Execute
Actually perform changes. Without this switch, the script runs in WhatIf mode.

.EXAMPLE
./scripts/apply-repo-rename-workspace.ps1

.EXAMPLE
./scripts/apply-repo-rename-workspace.ps1 -Execute -GitHubOwner kajencik
#>

[CmdletBinding(SupportsShouldProcess = $true, ConfirmImpact = 'Medium')]
param(
    [string]$BundlePath,

    [ValidateNotNullOrEmpty()]
    [string]$SyncRoot = (Join-Path $env:USERPROFILE 'OneDrive\VSCode\sync'),

    [ValidateNotNullOrEmpty()]
    [string]$BundleName = 'repo-rename-sync',

    [string[]]$WorkspaceSearchRoots = @(
        (Join-Path $env:USERPROFILE 'OneDrive\VSCode\workspaces'),
        (Join-Path $env:USERPROFILE 'Documents\VSCode\workspaces')
    ),

    [string[]]$RepoSearchRoots = @(
        (Join-Path $env:USERPROFILE 'source\repos'),
        (Join-Path $env:USERPROFILE 'OneDrive\source\repos'),
        (Join-Path $env:USERPROFILE 'Documents\repos')
    ),

    [string]$GitHubOwner,
    [switch]$SkipRepoRename,
    [switch]$SkipWorkspaceUpdate,
    [switch]$SkipGitRemoteUpdate,
    [switch]$Execute
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

if (-not $Execute) {
    $WhatIfPreference = $true
}

function Write-Step {
    param([string]$Message)
    Write-Host "[+] $Message" -ForegroundColor Cyan
}

function Write-WarnLine {
    param([string]$Message)
    Write-Host "[!] $Message" -ForegroundColor Yellow
}

function Get-ExistingPaths {
    param([string[]]$Paths)

    foreach ($path in @($Paths)) {
        if ([string]::IsNullOrWhiteSpace($path)) {
            continue
        }

        if (Test-Path -LiteralPath $path) {
            [System.IO.Path]::GetFullPath($path)
        }
    }
}

function Resolve-BundlePath {
    param(
        [string]$ExplicitBundlePath,
        [string]$SyncRootPath,
        [string]$NamePrefix
    )

    if (-not [string]::IsNullOrWhiteSpace($ExplicitBundlePath)) {
        $resolved = [System.IO.Path]::GetFullPath($ExplicitBundlePath)
        if (-not (Test-Path -LiteralPath $resolved)) {
            throw "BundlePath not found: $resolved"
        }

        return $resolved
    }

    # If the script is executed from inside a bundle's scripts/ folder,
    # prefer that adjacent bundle root before searching SyncRoot.
    $scriptPath = $PSCommandPath
    if ([string]::IsNullOrWhiteSpace($scriptPath)) {
        $scriptPath = $MyInvocation.PSCommandPath
    }

    $scriptDir = $null
    if (-not [string]::IsNullOrWhiteSpace($scriptPath)) {
        $scriptDir = Split-Path -Parent $scriptPath
    }
    if (-not [string]::IsNullOrWhiteSpace($scriptDir)) {
        $bundleFromScript = Split-Path -Parent $scriptDir
        $manifestNearby = Join-Path $bundleFromScript 'rename-sync-manifest.json'
        if (Test-Path -LiteralPath $manifestNearby) {
            return [System.IO.Path]::GetFullPath($bundleFromScript)
        }
    }

    $resolvedRoot = [System.IO.Path]::GetFullPath($SyncRootPath)
    if (-not (Test-Path -LiteralPath $resolvedRoot)) {
        throw "SyncRoot not found: $resolvedRoot"
    }

    $latest = Get-ChildItem -LiteralPath $resolvedRoot -Directory -Filter ("{0}-*" -f $NamePrefix) |
        Sort-Object -Property LastWriteTimeUtc -Descending |
        Select-Object -First 1

    if (-not $latest) {
        throw "No bundle found under $resolvedRoot matching $NamePrefix-*"
    }

    return $latest.FullName
}

function Normalize-WorkspaceRelativePath {
    param(
        [string]$RelativePath,
        [string]$RootLeaf
    )

    if ([string]::IsNullOrWhiteSpace($RelativePath)) {
        return $RelativePath
    }

    $normalized = ($RelativePath -replace '\\', '/')
    if ([string]::IsNullOrWhiteSpace($RootLeaf)) {
        return $normalized
    }

    $prefix = "$RootLeaf/"
    while ($normalized.StartsWith($prefix, [System.StringComparison]::OrdinalIgnoreCase)) {
        $normalized = $normalized.Substring($prefix.Length)
    }

    return $normalized
}

function Convert-OriginUrl {
    param(
        [string]$OriginUrl,
        [string]$NewRepoName,
        [string]$OwnerOverride
    )

    if ([string]::IsNullOrWhiteSpace($OriginUrl)) {
        return $null
    }

    $owner = $OwnerOverride

    if ($OriginUrl -match '^https://github.com/([^/]+)/([^/]+?)(\.git)?$') {
        if ([string]::IsNullOrWhiteSpace($owner)) {
            $owner = $matches[1]
        }
        return "https://github.com/$owner/$NewRepoName.git"
    }

    if ($OriginUrl -match '^git@github.com:([^/]+)/([^/]+?)(\.git)?$') {
        if ([string]::IsNullOrWhiteSpace($owner)) {
            $owner = $matches[1]
        }
        return "git@github.com:$owner/$NewRepoName.git"
    }

    return $null
}

$resolvedBundlePath = Resolve-BundlePath -ExplicitBundlePath $BundlePath -SyncRootPath $SyncRoot -NamePrefix $BundleName
$manifestPath = Join-Path $resolvedBundlePath 'rename-sync-manifest.json'

if (-not (Test-Path -LiteralPath $manifestPath)) {
    throw "Manifest not found: $manifestPath"
}

$manifest = Get-Content -LiteralPath $manifestPath -Raw | ConvertFrom-Json
$oldRepoName = [string]$manifest.oldRepoName
$newRepoName = [string]$manifest.newRepoName
$workspaceEntries = @($manifest.workspaceFiles)

if ([string]::IsNullOrWhiteSpace($oldRepoName) -or [string]::IsNullOrWhiteSpace($newRepoName)) {
    throw 'Manifest is missing oldRepoName/newRepoName.'
}

$existingWorkspaceRoots = @(Get-ExistingPaths -Paths $WorkspaceSearchRoots)
$existingRepoRoots = @(Get-ExistingPaths -Paths $RepoSearchRoots)

Write-Step "Using bundle: $resolvedBundlePath"
Write-Host "Old repo name: $oldRepoName"
Write-Host "New repo name: $newRepoName"
if (-not $Execute) {
    Write-WarnLine 'Dry-run mode active (WhatIf). Re-run with -Execute to apply changes.'
}

if (-not $SkipRepoRename) {
    Write-Step 'Renaming local repo folders where needed'

    foreach ($root in $existingRepoRoots) {
        $oldPath = Join-Path $root $oldRepoName
        $newPath = Join-Path $root $newRepoName

        if (-not (Test-Path -LiteralPath $oldPath)) {
            continue
        }

        if (Test-Path -LiteralPath $newPath) {
            Write-WarnLine "Target exists, skipping rename: $newPath"
            continue
        }

        if ($PSCmdlet.ShouldProcess($oldPath, "Rename folder to $newRepoName")) {
            Rename-Item -LiteralPath $oldPath -NewName $newRepoName
        }
    }
}

if (-not $SkipWorkspaceUpdate) {
    Write-Step 'Replacing local workspace files with patched bundle copies'
    $processedWorkspaceTargets = New-Object 'System.Collections.Generic.HashSet[string]'

    foreach ($entry in $workspaceEntries) {
        $wasPatched = [bool]$entry.oldRepoNameFound
        if (-not $wasPatched) {
            continue
        }

        $relativePath = [string]$entry.relativePath
        if ([string]::IsNullOrWhiteSpace($relativePath)) {
            continue
        }

        $sourceRootName = if ($entry.root) { Split-Path -Leaf ([string]$entry.root) } else { $null }
        $relativePath = Normalize-WorkspaceRelativePath -RelativePath $relativePath -RootLeaf $sourceRootName
        $patchedCandidates = @()
        if (-not [string]::IsNullOrWhiteSpace($sourceRootName)) {
            $patchedCandidates += Join-Path (Join-Path (Join-Path $resolvedBundlePath 'workspaces\patched') $sourceRootName) ($relativePath -replace '/', '\\')
        }
        $patchedCandidates += Join-Path (Join-Path (Join-Path $resolvedBundlePath 'workspaces\patched') 'workspace-root') ($relativePath -replace '/', '\\')

        $patchedPath = $patchedCandidates | Where-Object { Test-Path -LiteralPath $_ } | Select-Object -First 1
        if (-not $patchedPath) {
            Write-WarnLine "Patched copy not found for $relativePath"
            continue
        }

        $rootCandidates = @()
        if (-not [string]::IsNullOrWhiteSpace($sourceRootName)) {
            $rootCandidates += $existingWorkspaceRoots | Where-Object { (Split-Path -Leaf $_) -ieq $sourceRootName }
        }
        $rootCandidates += $existingWorkspaceRoots
        $rootCandidates = $rootCandidates | Select-Object -Unique

        if (@($rootCandidates).Count -eq 0) {
            Write-WarnLine "No local workspace roots found to apply $relativePath"
            continue
        }

        $targetPath = $null
        foreach ($root in $rootCandidates) {
            $candidate = Join-Path $root ($relativePath -replace '/', '\\')
            if (Test-Path -LiteralPath $candidate) {
                $targetPath = $candidate
                break
            }
        }

        if (-not $targetPath) {
            $targetPath = Join-Path ($rootCandidates[0]) ($relativePath -replace '/', '\\')
            $parent = Split-Path -Parent $targetPath
            if ($PSCmdlet.ShouldProcess($parent, 'Create workspace folder path')) {
                New-Item -ItemType Directory -Path $parent -Force | Out-Null
            }
        }

        if ($processedWorkspaceTargets.Contains($targetPath)) {
            continue
        }
        $processedWorkspaceTargets.Add($targetPath) | Out-Null

        if ($PSCmdlet.ShouldProcess($targetPath, 'Replace workspace file with patched bundle copy')) {
            Copy-Item -LiteralPath $patchedPath -Destination $targetPath -Force
        }
    }
}

if (-not $SkipGitRemoteUpdate) {
    Write-Step 'Updating git origin URLs for renamed repo folders'

    $git = Get-Command git -ErrorAction SilentlyContinue
    if (-not $git) {
        Write-WarnLine 'git command not found. Skipping remote URL updates.'
    } else {
        foreach ($root in $existingRepoRoots) {
            $repoPath = Join-Path $root $newRepoName
            if (-not (Test-Path -LiteralPath (Join-Path $repoPath '.git'))) {
                continue
            }

            $currentOrigin = (& $git.Source -C $repoPath remote get-url origin 2>$null)
            if ([string]::IsNullOrWhiteSpace($currentOrigin)) {
                Write-WarnLine "No origin remote found in $repoPath"
                continue
            }

            $targetOrigin = Convert-OriginUrl -OriginUrl $currentOrigin.Trim() -NewRepoName $newRepoName -OwnerOverride $GitHubOwner
            if ([string]::IsNullOrWhiteSpace($targetOrigin)) {
                Write-WarnLine "Could not derive GitHub URL from origin '$currentOrigin' in $repoPath"
                continue
            }

            if ($currentOrigin.Trim() -eq $targetOrigin) {
                continue
            }

            if ($PSCmdlet.ShouldProcess($repoPath, "Set origin URL to $targetOrigin")) {
                & $git.Source -C $repoPath remote set-url origin $targetOrigin
            }
        }
    }
}

Write-Host ''
Write-Host '[OK] Rename bundle apply flow completed.' -ForegroundColor Green
if (-not $Execute) {
    Write-Host 'Dry run only. Re-run with -Execute to perform changes.' -ForegroundColor Yellow
}
